version: '3.8'

services:
  my-holiday-app:
    image: node:16
    container_name: my-holiday-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"