name: Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 # Opdateret til nyeste version
    - uses: actions/setup-node@v3 # Opdateret til nyeste version
      with:
        node-version: '21.5.0' # Seneste 'Current' version af Node.js
    - run: npm install
    - run: npm run build
    - run: npm run test
    - run: npm run deploy
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}