name: Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '21.5.0'
    - run: npm install
    - run: npm run build
    - run: npm run test

    # Tilføj disse to nye trin for at sætte Git brugeridentitet
    - name: Set Git User
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - run: npm run deploy
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
